### ISSUE TITLE
[Question] when is kotatogram source going to update to later tdesktop

### ISSUE THREAD

**Issue by pokurt** [kotatogram/kotatogram-desktop#111]
nothing much but the latest update was released on may 11. was wondering when next release is going to be

**Comment by RadRussianRus** [comment]
I'm not giving any ETA's unless I'm sure in them.

Kotatogram is a project I'm working on in my spare time and when I have desire to work on it. I'm not planning to abandon it, since I'm using it on a daily basis, but there could be delays in updates. Even updating source takes time, especially with constantly changing internal TDesktop APIs. And time for updating sources scales with every new feature because of growing merge conflicts. And that's only source updates, not development of new features or bugfixes (yes, they could take siginficant time too, especially when there is a problem with debugging them).

I know that you need new features (either official or custom). But please, keep in mind all what I said above.

* * *

Regarding "latest update was released on may 11". You probably meant stable release (1.3.5). Latest beta release, 1.3.9, [was released September 9th](https://github.com/kotatogram/kotatogram-desktop/releases/tag/k1.3.9). There are some bugs which I'm planning to solve and then release stable version, so if you have no fear of betas, you can try it. If you want stable version, waiting is the only answer here.

**Comment by RadRussianRus** [comment]
Further discussion will be at https://github.com/kotatogram/kotatogram-desktop/discussions/119.
