### ISSUE TITLE
[Question] Nimf not supported in Kotatogram Flatpak

### ISSUE THREAD

**Issue by opqriu** [kotatogram/kotatogram-desktop#14]
https://github.com/hamonikr/nimf
I am using the CJK input methods that Nimf.
I am using a telegram from web.telegram.org in Browser.
The kotatogram Flatpak Version impossible in the Korean Input.
Should you ever can be resolved?

**Comment by ilya-fedin** [comment]
As far as I know, input plugins are in kde runtime :thinking: 
Wonder if we can add other plugins...

**Comment by ilya-fedin** [comment]
There are ibus (included in qt) and [fcitx](https://github.com/KDE/flatpak-kde-runtime/blob/master/org.kde.Sdk.json#L925) input plugins. Try to request nimf at [](https://bugs.kde.org/buglist.cgi?component=general&list_id=1727364&product=Qt%2FKDE%20Flatpak%20Runtime&resolution=---), so that all qt apps in flatpak will support nimf
