### ISSUE TITLE
how to learn telegram codes?

### ISSUE THREAD

**Issue by AMP999** [kotatogram/kotatogram-desktop#271]
since you've successfully understood telegram codes and manipulated them, I think it's the best place to ask my question.
I'm learning c++ and I'm trying to comprehend telegram codes and manipulate them. but I don't know where and how to start.
my confusion is about Desktop App Toolkit repository which telegram has made for it's usage but hasn't made any documentation around it so I can't look at this repository as a black box and use it like for example Qt.
should I start with Desktop App Toolkit repository and document it for my self or what?
how did you overcome these problems? 
I will be grateful if you help me

**Comment by RadRussianRus** [comment]
Desktop App Toolkit was made specifically for Telegram Desktop and (currently discarded) Telegram Wallet. There is no documentation for it. Only way to work with it is reading the code and understanding what it does.

I suggest you to start with something easier (with documentation, at least) since you've only started learning. But if you really want to tinker with Telegram's code, you can build it yourself and then use good old trial-and-error method. Since Telegram heavily uses Qt, you may find its documentation helpful, along with C++ documentation.

**Comment by AMP999** [comment]
thank you
does kotatogram have any documentation by the way?

**Comment by RadRussianRus** [comment]
Sadly, no, I have no time for that. Maybe I'll write a documentation for Kotatogram's internal functions one day, but Telegram's code is changing frequently and changes are often breaking, so documenting them would be much harder than Kotatogram's.

**Comment by ilya-fedin** [comment]
> how did you overcome these problems?

I'm asking preston (the tdesktop developer) in PM on Telegram when I don't understand something. He doesn't always answer, but he explains basic things like how to use rpl/crl

**Comment by AMP999** [comment]
> I'm asking preston (the tdesktop developer) in PM on Telegram when I don't understand something. He doesn't always answer, but he explains basic things like how to use rpl/crl

this is great. but I don't have his telegram username. how can I get his username?
