### ISSUE TITLE
[Question] Windows x64 version?

### ISSUE THREAD

**Issue by HitaloSama** [kotatogram/kotatogram-desktop#33]
I installed Kotatogram on Windows 10 x64 but the installer installs the x86 version of Kotatogram, I was wondering if the Kotatogram would have an x64 version for Windows?

**Comment by RadRussianRus** [comment]
Is there a specific need in it? Windows has fine backward compatibility for 32-bits. Also, since release linking is long (~3h), it's easier to build 32-builds to support both 32 and 64. I think it's same reasoning for Telegram Desktop.

There could be a possibility for separate x64 builds if I'll make dynamically linked builds, but I don't know when will it happen.
