### ISSUE TITLE
[Feature Request] Translation and Auto-translate of messages

### ISSUE THREAD

**Issue by thiccpad** [kotatogram/kotatogram-desktop#330]
### Is your feature request related to a problem?

In several Telegram Android Forks (and I think FOSS too) you can turn translate messages by clicking on them and a possibility to translate all text if you're for example browsing a foreign language channel.

### Describe the solution you'd like

Create a menu where you can choose different translation providers and languages, a feature for autotranslating and an option to exclude one or multiple languages from translation. A screenshot of how it's handled in Nekogram:

![image](https://user-images.githubusercontent.com/70910286/157280409-b8f57cd7-901d-44ac-ab69-eea0949c8066.png)

### Describe alternatives you've considered

.

**Comment by hkfsc** [comment]
What's the name of client you are using on Android?

**Comment by hkfsc** [comment]
Hard to implement, even the official version not support translation feature so far...
And if Kotatogram use its own way to support it, then might will have some conflicts when official version finally update this necessary feature.

However, The [official repo](https://github.com/telegramdesktop/tdesktop/issues/6707) might will never implement this feature, because the consideration of privacy, though I think Nekogram find its only way to go: provide enough third-party translation API, and let users choose the API they want to use, then do the in-app translation tasks.
[Check here](https://gitlab.com/Nekogram/Nekogram/-/tree/main/TMessagesProj/src/main/java/tw/nekomimi/nekogram/translator)

**Comment by hkfsc** [comment]
https://github.com/telegramdesktop/tdesktop/issues/6707

**Comment by EricKotato** [comment]
TDesktop 4.3.2 now has it, so I'm closing this issue, since Kotatogram after source code update will have it automatically.
