### ISSUE TITLE
Can't watch streams

### ISSUE THREAD

**Issue by TechnoMasterBoy** [kotatogram/kotatogram-desktop#399]
### Steps to reproduce

1. Open kotatogram
2. Play any stream

### Expected behaviour

Stream is supposed to play.

### Actual behaviour

Stream does not play and gives error message "In order to join the livestream, please update your Telegram application to the latest version."
Yes, I've tried using latest beta aswell but no luck. But I see Kotatogram hasn't updated since december 2021... Maybe time for you guys to update the program? Like, your program is ages behind in updates. Current Telegram is 4.2.4 while yours is 3.5.2...

### Operating system

Windows 10

### Version of Kotatogram Desktop

1.4.9 Beta x64 (TD 3.5.2)

### Installation source

Static binary from official website

**Comment by TechnoMasterBoy** [comment]
Also normal telegram which is way ahead in updates has like 3 times more reactions you can use on messages. Making Kotatogram a very unappealing choice when it's lagging this far behind.

**Comment by EricKotato** [comment]
It will be updated soon. Please do not create issues for features that will be added with source code update.

**Comment by TechnoMasterBoy** [comment]
> It will be updated soon. Please do not create issues for features that will be added with source code update.

How am I supposed to know you were planning to update all of a sudden?
It is a perfectly valid reason to make an issue, because it is just that, an issue.
Just because the issues go away after you update, doesn't mean I can't complain when you don't update...

**Comment by EricKotato** [comment]
> How am I supposed to know you were planning to update all of a sudden?

Because there wasn't any announcement saying that Kotatogram is abandoned. 

> It is a perfectly valid reason to make an issue, because it is just that, an issue.

I understand your point, but there are many similar issues were created. They won't help me as a developer to ship update any faster.

> Just because the issues go away after you update, doesn't mean I can't complain when you don't update...

You can, but again: it doesn't help. People constantly asking me about update in chats, so it's impossible to forget about this.

**Comment by TechnoMasterBoy** [comment]
> Because there wasn't any announcement saying that Kotatogram is abandoned.

It has been an entire YEAR.
That's pretty much the same as abandoned.

> They won't help me as a developer to ship update any faster.

Should maybe not go into hibernation then lol.

> so it's impossible to forget about this.

Based on how long it has taken you, I'd say it is in fact possible.

**Comment by EricKotato** [comment]
> It has been an entire YEAR.
> That's pretty much the same as abandoned.

Kotatogram is the project I'm working on in my spare time. If I don't have enough time, there will be inevitable update delay.

> Should maybe not go into hibernation then lol.

That's not the reason. Issues like these are wasting my time because I'm taking my time to reply to them, while I've answered this question multiple times (see https://github.com/kotatogram/kotatogram-desktop/discussions/119#discussioncomment-173540, #373, #377, #380, #391, #394).

Maybe if you've searched before posting a new issue, you'd knew that.

> Based on how long it has taken you, I'd say it is in fact possible.

Again: I've reminded of that multiple times. These issues remind me, chats remind me, even "This message is not supported" reminds me, because I'm using Kotatogram myself. So it's not possible.


BTW, there is a [patches-track](https://github.com/kotatogram/kotatogram-desktop/tree/patches-track) branch that resembles current update progress, which is currently based on TD 3.7.3, and will be merged into `dev` when it's on par with TDesktop's dev.

**Comment by K14Mua** [comment]
I'm sorry. Is it difficult to just update the telegram version on which catogram is based without updating the new functions of catogram? Just take a fresh telegram client and roll the existing version of the kotogram from above.

**Comment by EricKotato** [comment]
It's not that easy as you say.

Kotatogram is a fork which adds new features on top of existing ones. It would be fine if Telegram Desktop had stable internal APIs. However, that's not the case here.

Since internal APIs of Telegram Desktop are unstable, Kotatogram features can (and probably will) break. Some source code updates may break no features at all. And some can break them so hard that it's better to either remove the feature entirely or rewrite it.

Feature is usually removed when it makes no sense anymore (e.g. implemented in TDesktop). It was hard before, so I've started to make [patches-track](https://github.com/kotatogram/kotatogram-desktop/tree/patches-track) branch, and now it's easy enough.

Rewriting features is a different story. With new branch it's easier to track neccessary changes and adapt them to new code, but sometimes it's hard even with this help.

If it was simple "rebase on top of latest TDesktop" with absolutely no merge conflicts or broken features, it would be updated much faster. But with multitude of breaking changes that takes a lot of time and currently I don't have enough time for that.

However, that doesn't mean that Kotatogram is abandoned. I'll be back to source code updating as soon as I have enough time.
