### ISSUE TITLE
[Feature Request] Rearrange folders (including All Chats), load the first one by default

### ISSUE THREAD

**Issue by SleeplessSloth** [kotatogram/kotatogram-desktop#49]
### Is your feature request related to a problem?
No

### Describe the solution you'd like
Most importantly, I'd like to be able to open my "Personal" folder by default. I believe the most intuitive way to accomplish this would be to allow the folders, including the "All Chats" folder, to be rearranged and the top one to be loaded by default.
My personally favorable arrangement would be something like:
1. Personal
2. Channels
3. All Chats

### Describe alternatives you've considered
For the time being, every time I open telegram, I press Ctrl+2 but that's really uncomfortable

**Comment by RadRussianRus** [comment]
There is already "Default folder" feature since Kotatogram 1.2.1. It will be opened on app start, or pressing Esc with chat closed.

You can set it by right-clicking on folder in panel, and choosing "Make folder default".
![](https://user-images.githubusercontent.com/2903496/82474728-2b64ec00-9ad4-11ea-8fa6-9a754b32f99f.png)

As an alternative, you can set it when creating or editing folder (enabling the "Default folder" checkbox):
![](https://user-images.githubusercontent.com/2903496/82474915-6b2bd380-9ad4-11ea-9772-973374415c6e.png)

"All Chats" folder can't be moved, but can be hidden since Kotatogram 1.2.2. You still can switch to it by shortcuts though.

You can hide it in Settings > Kotatogram Settings > Hide "All Chats" folder:
![](https://user-images.githubusercontent.com/2903496/82475213-d2498800-9ad4-11ea-900c-3b6b1ee6a34a.png)

For now I won't risk to move "All Chats" folder, since it's a static one, and others are dynamic, but maybe I'll think on something in future.

**Comment by SleeplessSloth** [comment]
I searched throughout all the settings in the settings menu and never though to right-click it. Thanks!
