### ISSUE TITLE
[Feature Request] Translation of posts

### ISSUE THREAD

**Issue by TomTheDragon** [kotatogram/kotatogram-desktop#59]
### Is your feature request related to a problem?
No.

### Describe the solution you'd like
It would be great to have a feature to translate posts into a different language. This could be done by right clicking and selecting a button on the posts.

### Additional context
I seen this recently in the newest version of Plus (alternative for the android client) and it works great.

**Comment by RadRussianRus** [comment]
It's good feature, but:
1. Context menus will grow. It's bad since they are already big, and if they will be too big, you can easily lost in them. So that's why I'm trying to add options carefully.
2. It's possible that it will lead to additional dependencies. Not necessarily, but it's possible.

If I'll find a way how to deal with it, then I'll make it.

**Comment by TomTheDragon** [comment]
Like i said i seen it on Plus and i think it still looks ok on a phone screen, but maybe there is a better way to do it.
A second row maybe?

**Comment by RadRussianRus** [comment]
I'll think of it.

**Comment by ilya-fedin** [comment]
>     2\. It's possible that it will lead to additional dependencies. Not necessarily, but it's possible.

The most big problem is that all translation services require a token that is not free on most translation services

Plus may have monetization

**Comment by EricKotato** [comment]
TDesktop 4.3.2 now has it, so I'm closing this issue, since Kotatogram after source code update will have it automatically.
